export interface imageGalleryData {
  src: string;
  alt: string;
  cat: string[];
  width: number;
  height: number;
}

const imageGallery: imageGalleryData[] = [
  {
    src: "/img/couple/couple3.jpg",
    alt: "Description de la photo 3",
    cat: ["couple"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/famille/fam1.jpg",
    alt: "Description de la photo 1",
    cat: ["famille"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/mariage/mariage5.jpg",
    alt: "Description de la photo 5",
    cat: ["mariage"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/maternite/mat1.jpg",
    alt: "Description de la photo 1",
    cat: ["maternite"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/portrait/port1.jpg",
    alt: "Description de la photo 1",
    cat: ["portrait"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/professionnel/pro1.jpg",
    alt: "Description de la photo 1",
    cat: ["professionnel"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/famille/fam2.jpg",
    alt: "Description de la photo 2",
    cat: ["famille"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/couple/couple1.jpg",
    alt: "Description de la photo 1",
    cat: ["couple"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/mariage/mariage6.jpg",
    alt: "Description de la photo 6",
    cat: ["mariage"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/maternite/mat3.jpg",
    alt: "Description de la photo 3",
    cat: ["maternite"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/portrait/port2.jpg",
    alt: "Description de la photo 2",
    cat: ["portrait"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/professionnel/pro4.jpg",
    alt: "Description de la photo 4",
    cat: ["professionnel"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/couple/couple2.jpg",
    alt: "Description de la photo 2",
    cat: ["couple"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/mariage/mariage1.jpg",
    alt: "Description de la photo 1",
    cat: ["mariage"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/famille/fam3.jpg",
    alt: "Description de la photo 3",
    cat: ["famille"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/professionnel/pro2.jpg",
    alt: "Description de la photo 2",
    cat: ["professionnel"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/maternite/mat5.jpg",
    alt: "Description de la photo 5",
    cat: ["maternite"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/famille/fam4.jpg",
    alt: "Description de la photo 4",
    cat: ["famille"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/mariage/mariage2.jpg",
    alt: "Description de la photo 2",
    cat: ["mariage"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/couple/couple4.jpg",
    alt: "Description de la photo 4",
    cat: ["couple"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/maternite/mat4.jpg",
    alt: "Description de la photo 4",
    cat: ["maternite"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/portrait/port3.jpg",
    alt: "Description de la photo 3",
    cat: ["portrait"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/professionnel/pro3.jpg",
    alt: "Description de la photo 3",
    cat: ["professionnel"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/famille/fam5.jpg",
    alt: "Description de la photo 5",
    cat: ["famille"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/couple/couple5.jpg",
    alt: "Description de la photo 5",
    cat: ["couple"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/mariage/mariage3.jpg",
    alt: "Description de la photo 3",
    cat: ["mariage"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/famille/fam6.jpg",
    alt: "Description de la photo 6",
    cat: ["famille"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/professionnel/pro5.jpg",
    alt: "Description de la photo 5",
    cat: ["professionnel"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/maternite/mat6.jpg",
    alt: "Description de la photo 6",
    cat: ["maternite"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/portrait/port4.jpg",
    alt: "Description de la photo 4",
    cat: ["portrait"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/mariage/mariage4.jpg",
    alt: "Description de la photo 4",
    cat: ["mariage"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/famille/fam7.jpg",
    alt: "Description de la photo 7",
    cat: ["famille"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/portrait/port5.jpg",
    alt: "Description de la photo 5",
    cat: ["portrait"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/professionnel/pro6.jpg",
    alt: "Description de la photo 6",
    cat: ["professionnel"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/mariage/mariage7.jpg",
    alt: "Description de la photo 7",
    cat: ["mariage"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/couple/couple6.jpg",
    alt: "Description de la photo 6",
    cat: ["couple"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/mariage/mariage8.jpg",
    alt: "Description de la photo 8",
    cat: ["mariage"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/portrait/port6.jpg",
    alt: "Description de la photo 6",
    cat: ["portrait"],
    width: 853,
    height: 1280,
  },
  {
    src: "/img/famille/fam8.jpg",
    alt: "Description de la photo 8",
    cat: ["famille"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/naissance/born1.jpg",
    alt: "Description de la photo 1",
    cat: ["born"],
    width: 1280,
    height: 851,
  },
  {
    src: "/img/naissance/born2.jpg",
    alt: "Description de la photo 2",
    cat: ["born"],
    width: 1280,
    height: 851,
  },
];

export default imageGallery;
